import { ChemicalSubstance } from "./dwsimChemicals";

/** Reagents referenced by the 115-experiment catalog that were missing from the core library. */
export const MISSING_CHEMICAL_DATABASE: Record<string, ChemicalSubstance> = {
  chloroform_reagent: {
    id: "chloroform_reagent", name: "Chloroform (Trichloromethane)", formula: "CHCl3(l)", state: "liquid",
    color: "rgba(255,255,255,0.18)", opacity: 0.18, pH: 7, molarMass: 119.4, boilingPoint: 61.2,
    description: "Dense, non-polar solvent that sinks below water. Used to extract halogens — iodine gives a violet lower layer, bromine an orange-brown one.",
    hazards: ["Harmful vapour", "Suspected carcinogen"],
  },
  pb_no3_sol: {
    id: "pb_no3_sol", name: "Lead(II) Nitrate Solution (0.1M)", formula: "Pb(NO3)2(aq)", state: "solution",
    color: "rgba(255,255,255,0.2)", opacity: 0.2, pH: 5.5, molarMass: 331.2,
    description: "Soluble lead salt. Gives a bright yellow precipitate with iodide and a white precipitate with chloride that dissolves on heating.",
    hazards: ["Toxic", "Environmental hazard"],
  },
  kno3_sol: {
    id: "kno3_sol", name: "Potassium Nitrate Solution (0.1M)", formula: "KNO3(aq)", state: "solution",
    color: "rgba(255,255,255,0.2)", opacity: 0.2, pH: 7, molarMass: 101.1,
    description: "Neutral nitrate salt. Electrolyte used in salt bridges and in solubility/crystallisation studies.",
    hazards: ["Oxidiser"],
  },
  nh4no3_solid: {
    id: "nh4no3_solid", name: "Ammonium Nitrate (solid)", formula: "NH4NO3(s)", state: "solid",
    color: "rgba(250,250,250,1)", opacity: 1, pH: 5.5, molarMass: 80.0,
    description: "White crystalline salt whose dissolution in water is strongly endothermic — the temperature drops sharply.",
    hazards: ["Oxidiser", "Irritant"],
  },
  nahco3_solid: {
    id: "nahco3_solid", name: "Sodium Hydrogencarbonate (solid)", formula: "NaHCO3(s)", state: "solid",
    color: "rgba(252,252,252,1)", opacity: 1, pH: 8.3, molarMass: 84.0,
    description: "White powder that fizzes with acid and decomposes on heating to give CO2 and water (thermal decomposition).",
    hazards: [],
  },
  cuco3_solid: {
    id: "cuco3_solid", name: "Copper(II) Carbonate (solid)", formula: "CuCO3(s)", state: "solid",
    color: "rgba(60,160,140,1)", opacity: 1, pH: 7, molarMass: 123.6,
    description: "Green powder that turns black copper(II) oxide on heating, releasing CO2 that turns limewater milky.",
    hazards: ["Harmful if swallowed"],
  },
  cuo_solid: {
    id: "cuo_solid", name: "Copper(II) Oxide (solid)", formula: "CuO(s)", state: "solid",
    color: "rgba(30,30,32,1)", opacity: 1, pH: 7, molarMass: 79.5,
    description: "Black basic oxide. Reduced to pink-brown copper by hydrogen or carbon; dissolves in warm acid to give a blue solution.",
    hazards: ["Harmful"],
  },
  zn_no3_sol: {
    id: "zn_no3_sol", name: "Zinc Nitrate Solution (0.1M)", formula: "Zn(NO3)2(aq)", state: "solution",
    color: "rgba(255,255,255,0.2)", opacity: 0.2, pH: 5.5, molarMass: 189.4, isAmphoteric: true,
    description: "Zinc(II) salt. White precipitate with NaOH that redissolves in excess alkali and in excess ammonia.",
    hazards: ["Irritant", "Oxidiser"],
  },
  znso4_sol: {
    id: "znso4_sol", name: "Zinc Sulfate Solution (1M)", formula: "ZnSO4(aq)", state: "solution",
    color: "rgba(255,255,255,0.2)", opacity: 0.2, pH: 5.5, molarMass: 161.5,
    description: "Half-cell electrolyte for the zinc electrode in the Daniell cell.",
    hazards: ["Irritant"],
  },
  mgso4_sol: {
    id: "mgso4_sol", name: "Magnesium Sulfate Solution (0.1M)", formula: "MgSO4(aq)", state: "solution",
    color: "rgba(255,255,255,0.2)", opacity: 0.2, pH: 6.5, molarMass: 120.4,
    description: "Source of Mg2+ hardness ions in EDTA water-hardness titrations; white precipitate with NaOH, insoluble in excess.",
    hazards: [],
  },
  k3fecn6_sol: {
    id: "k3fecn6_sol", name: "Potassium Hexacyanoferrate(III) Indicator", formula: "K3[Fe(CN)6](aq)", state: "solution",
    color: "rgba(210,180,40,0.6)", opacity: 0.6, pH: 7, molarMass: 329.2,
    description: "Rusting indicator. Gives an intense Prussian-blue colour wherever Fe2+ is released at the anodic sites of a nail.",
    hazards: ["Irritant"],
  },
  agar_gel: {
    id: "agar_gel", name: "Agar Jelly (indicator gel)", formula: "agar", state: "solution",
    color: "rgba(235,235,215,0.55)", opacity: 0.55, pH: 7, molarMass: 300,
    description: "Warm gel that sets around iron nails, freezing the blue and pink rusting-indicator zones in place for observation.",
    hazards: ["Hot when poured"],
  },
  buffer_ph4: {
    id: "buffer_ph4", name: "Buffer Solution pH 4.00", formula: "buffer", state: "solution",
    color: "rgba(255,120,120,0.25)", opacity: 0.25, pH: 4, molarMass: 100,
    description: "Standard acidic buffer used to calibrate a pH meter.",
    hazards: [],
  },
  buffer_ph7: {
    id: "buffer_ph7", name: "Buffer Solution pH 7.00", formula: "buffer", state: "solution",
    color: "rgba(140,220,150,0.25)", opacity: 0.25, pH: 7, molarMass: 100,
    description: "Standard neutral buffer used as the first calibration point on a pH meter.",
    hazards: [],
  },
  buffer_ph10: {
    id: "buffer_ph10", name: "Buffer Solution pH 10.00", formula: "NH3/NH4Cl", state: "solution",
    color: "rgba(120,160,240,0.25)", opacity: 0.25, pH: 10, molarMass: 100,
    description: "Alkaline ammonia buffer — also holds the pH for EDTA complexometric titrations with Eriochrome Black T.",
    hazards: ["Irritant"],
  },
  alumina_catalyst: {
    id: "alumina_catalyst", name: "Alumina Catalyst (porous pot)", formula: "Al2O3(s)", state: "solid",
    color: "rgba(240,238,232,1)", opacity: 1, pH: 7, molarMass: 102.0,
    description: "Heterogeneous cracking catalyst. Strongly heated with paraffin it breaks long alkanes into alkenes that decolourise bromine water.",
    hazards: ["Dust irritant"],
  },
  catalase_sol: {
    id: "catalase_sol", name: "Catalase Suspension (liver/yeast)", formula: "enzyme", state: "solution",
    color: "rgba(200,150,140,0.5)", opacity: 0.5, pH: 7, molarMass: 250000,
    description: "Biological catalyst that decomposes hydrogen peroxide to water and oxygen extremely rapidly; denatured above ~60 °C.",
    hazards: ["Biological material"],
  },
  paraffin_oil: {
    id: "paraffin_oil", name: "Liquid Paraffin (medicinal)", formula: "CnH2n+2(l)", state: "liquid",
    color: "rgba(255,250,220,0.35)", opacity: 0.35, pH: 7, molarMass: 250, boilingPoint: 300, flammable: true,
    description: "Long-chain alkane mixture used as the feedstock for catalytic cracking.",
    hazards: ["Flammable"],
  },
  milk_sample: {
    id: "milk_sample", name: "Milk Sample", formula: "protein/fat", state: "solution",
    color: "rgba(252,252,248,0.95)", opacity: 0.95, pH: 6.7, molarMass: 200,
    description: "Food sample containing protein (violet with Biuret) and fat (red top layer with Sudan III).",
    hazards: [],
  },
  egg_albumen: {
    id: "egg_albumen", name: "Egg Albumen Solution", formula: "protein", state: "solution",
    color: "rgba(250,250,235,0.6)", opacity: 0.6, pH: 8.0, molarMass: 200,
    description: "Protein solution — gives Ruhemann's purple with ninhydrin and a violet Biuret result; coagulates white on heating.",
    hazards: [],
  },
  spinach_extract: {
    id: "spinach_extract", name: "Spinach Leaf Extract (pigments)", formula: "pigment mix", state: "solution",
    color: "rgba(40,120,50,0.85)", opacity: 0.85, pH: 6.5, molarMass: 400,
    description: "Green pigment mixture separated by TLC into chlorophyll a, chlorophyll b, xanthophyll and carotene bands.",
    hazards: [],
  },
  starch_solid: {
    id: "starch_solid", name: "Starch (solid)", formula: "(C6H10O5)n", state: "solid",
    color: "rgba(252,252,250,1)", opacity: 1, pH: 7, molarMass: 162,
    description: "White polysaccharide powder. Gives a blue-black colour with iodine; hydrolysed by acid or amylase to reducing sugars.",
    hazards: [],
  },
  propanone: {
    id: "propanone", name: "Propanone (Acetone)", formula: "CH3COCH3(l)", state: "liquid",
    color: "rgba(255,255,255,0.18)", opacity: 0.18, pH: 7, molarMass: 58.1, boilingPoint: 56.1, flammable: true,
    description: "Volatile ketone. No reaction with Fehling's or Tollens', distinguishing it from an aldehyde; positive iodoform test.",
    hazards: ["Highly Flammable", "Irritant"],
  },
  ethyl_ethanoate: {
    id: "ethyl_ethanoate", name: "Ethyl Ethanoate (ester)", formula: "CH3COOC2H5(l)", state: "liquid",
    color: "rgba(255,255,255,0.16)", opacity: 0.16, pH: 7, molarMass: 88.1, boilingPoint: 77.1, flammable: true,
    description: "Sweet, fruity-smelling ester formed by refluxing ethanol with ethanoic acid and concentrated sulfuric acid.",
    hazards: ["Highly Flammable", "Irritant"],
  },
  ethanedioic_acid: {
    id: "ethanedioic_acid", name: "Ethanedioic (Oxalic) Acid (0.05M)", formula: "H2C2O4(aq)", state: "solution",
    color: "rgba(255,255,255,0.2)", opacity: 0.2, pH: 1.8, molarMass: 90.0,
    description: "Primary standard reductant for standardising potassium manganate(VII); titrated hot at about 60 °C.",
    hazards: ["Toxic", "Corrosive"],
  },
  koh_sol: {
    id: "koh_sol", name: "Potassium Hydroxide Solution (0.1M)", formula: "KOH(aq)", state: "solution",
    color: "rgba(255,255,255,0.2)", opacity: 0.2, pH: 13.2, molarMass: 56.1,
    description: "Strong alkali. Also used as a CO2 absorbent in gas-volume experiments.",
    hazards: ["Corrosive"],
  },
  pb_acetate_paper: {
    id: "pb_acetate_paper", name: "Lead(II) Ethanoate Test Paper", formula: "Pb(CH3COO)2", state: "solution",
    color: "rgba(250,250,250,0.8)", opacity: 0.8, pH: 6, molarMass: 325.3,
    description: "Damp test paper that turns shiny black (PbS) in the presence of hydrogen sulfide gas.",
    hazards: ["Toxic"],
  },
  soda_lime: {
    id: "soda_lime", name: "Soda Lime (CO2 absorbent)", formula: "NaOH/CaO(s)", state: "solid",
    color: "rgba(235,235,225,1)", opacity: 1, pH: 13, molarMass: 60,
    description: "Granular absorbent that traps carbon dioxide in combustion analysis; also decarboxylates salts on strong heating.",
    hazards: ["Corrosive"],
  },
  cacl2_desiccant: {
    id: "cacl2_desiccant", name: "Anhydrous Calcium Chloride (desiccant)", formula: "CaCl2(s)", state: "solid",
    color: "rgba(248,248,248,1)", opacity: 1, pH: 7, molarMass: 111.0,
    description: "Deliquescent drying agent that traps water vapour in combustion-analysis and gas-drying trains.",
    hazards: ["Irritant"],
  },
  no2_n2o4_gas: {
    id: "no2_n2o4_gas", name: "NO2 / N2O4 Equilibrium Mixture", formula: "2NO2 ⇌ N2O4", state: "gas",
    color: "rgba(190,110,60,0.65)", opacity: 0.65, pH: 2, molarMass: 46.0,
    description: "Sealed equilibrium gas. Darkens brown when warmed (endothermic forward) and fades pale when cooled in ice — Le Chatelier in action.",
    hazards: ["Highly Toxic", "Oxidiser"],
  },
  n2_gas: {
    id: "n2_gas", name: "Nitrogen Gas", formula: "N2(g)", state: "gas",
    color: "rgba(220,225,235,0.25)", opacity: 0.25, pH: 7, molarMass: 28.0,
    description: "Inert, colourless gas. Extinguishes a burning splint and gives no reaction with limewater.",
    hazards: ["Asphyxiant"],
  },
  nh3_gas: {
    id: "nh3_gas", name: "Ammonia Gas", formula: "NH3(g)", state: "gas",
    color: "rgba(225,235,225,0.3)", opacity: 0.3, pH: 11, molarMass: 17.0,
    description: "Pungent alkaline gas. Turns damp red litmus blue and gives dense white smoke with concentrated HCl.",
    hazards: ["Toxic", "Corrosive vapour"],
  },
  ethene_gas: {
    id: "ethene_gas", name: "Ethene Gas", formula: "C2H4(g)", state: "gas",
    color: "rgba(230,230,230,0.25)", opacity: 0.25, pH: 7, molarMass: 28.1, flammable: true,
    description: "Unsaturated alkene from cracking. Rapidly decolourises bromine water and burns with a smoky flame.",
    hazards: ["Extremely Flammable"],
  },
};
