/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SyllabusRouteImport } from './routes/syllabus'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PeriodicTableRouteImport } from './routes/periodic-table'
import { Route as LabRouteImport } from './routes/lab'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChemicalsRouteImport } from './routes/chemicals'
import { Route as AtomBuilderRouteImport } from './routes/atom-builder'
import { Route as ApparatusRouteImport } from './routes/apparatus'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SyllabusRoute = SyllabusRouteImport.update({
  id: '/syllabus',
  path: '/syllabus',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PeriodicTableRoute = PeriodicTableRouteImport.update({
  id: '/periodic-table',
  path: '/periodic-table',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChemicalsRoute = ChemicalsRouteImport.update({
  id: '/chemicals',
  path: '/chemicals',
  getParentRoute: () => rootRouteImport,
} as any)
const AtomBuilderRoute = AtomBuilderRouteImport.update({
  id: '/atom-builder',
  path: '/atom-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ApparatusRoute = ApparatusRouteImport.update({
  id: '/apparatus',
  path: '/apparatus',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apparatus': typeof ApparatusRoute
  '/atom-builder': typeof AtomBuilderRoute
  '/chemicals': typeof ChemicalsRoute
  '/contact': typeof ContactRoute
  '/lab': typeof LabRoute
  '/periodic-table': typeof PeriodicTableRoute
  '/pricing': typeof PricingRoute
  '/syllabus': typeof SyllabusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apparatus': typeof ApparatusRoute
  '/atom-builder': typeof AtomBuilderRoute
  '/chemicals': typeof ChemicalsRoute
  '/contact': typeof ContactRoute
  '/lab': typeof LabRoute
  '/periodic-table': typeof PeriodicTableRoute
  '/pricing': typeof PricingRoute
  '/syllabus': typeof SyllabusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apparatus': typeof ApparatusRoute
  '/atom-builder': typeof AtomBuilderRoute
  '/chemicals': typeof ChemicalsRoute
  '/contact': typeof ContactRoute
  '/lab': typeof LabRoute
  '/periodic-table': typeof PeriodicTableRoute
  '/pricing': typeof PricingRoute
  '/syllabus': typeof SyllabusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/apparatus'
    | '/atom-builder'
    | '/chemicals'
    | '/contact'
    | '/lab'
    | '/periodic-table'
    | '/pricing'
    | '/syllabus'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/apparatus'
    | '/atom-builder'
    | '/chemicals'
    | '/contact'
    | '/lab'
    | '/periodic-table'
    | '/pricing'
    | '/syllabus'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/apparatus'
    | '/atom-builder'
    | '/chemicals'
    | '/contact'
    | '/lab'
    | '/periodic-table'
    | '/pricing'
    | '/syllabus'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApparatusRoute: typeof ApparatusRoute
  AtomBuilderRoute: typeof AtomBuilderRoute
  ChemicalsRoute: typeof ChemicalsRoute
  ContactRoute: typeof ContactRoute
  LabRoute: typeof LabRoute
  PeriodicTableRoute: typeof PeriodicTableRoute
  PricingRoute: typeof PricingRoute
  SyllabusRoute: typeof SyllabusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/syllabus': {
      id: '/syllabus'
      path: '/syllabus'
      fullPath: '/syllabus'
      preLoaderRoute: typeof SyllabusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/periodic-table': {
      id: '/periodic-table'
      path: '/periodic-table'
      fullPath: '/periodic-table'
      preLoaderRoute: typeof PeriodicTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chemicals': {
      id: '/chemicals'
      path: '/chemicals'
      fullPath: '/chemicals'
      preLoaderRoute: typeof ChemicalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atom-builder': {
      id: '/atom-builder'
      path: '/atom-builder'
      fullPath: '/atom-builder'
      preLoaderRoute: typeof AtomBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apparatus': {
      id: '/apparatus'
      path: '/apparatus'
      fullPath: '/apparatus'
      preLoaderRoute: typeof ApparatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApparatusRoute: ApparatusRoute,
  AtomBuilderRoute: AtomBuilderRoute,
  ChemicalsRoute: ChemicalsRoute,
  ContactRoute: ContactRoute,
  LabRoute: LabRoute,
  PeriodicTableRoute: PeriodicTableRoute,
  PricingRoute: PricingRoute,
  SyllabusRoute: SyllabusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
